
version: '3.8'

services:
  canara_app:
    image: shwe12/canara_shwe
    container_name: canara_app_shwe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    restart: always